services:
    _defaults:
        autowire: true
        autoconfigure: true

    Mb\DoctrineLogBundle\:
        resource: '../../*'
        exclude:
            - '../../DependencyInjection'
            - '../../Entity'
            - '../../Tests'
            - '../../MbDoctrineLogBundle.php'
            - '../../rector.php'
